# Generated by Django 4.2.13 on 2025-10-05 12:23

import business_forms.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('telegram', 'Телеграм'), ('instagram', 'Инстаграм (запрещен в РФ)'), ('bot_mailing', 'Рассылка в боте'), ('email_mailing', 'Рассылка по почте')], max_length=20, verbose_name='Вы увидели эту анкету у меня в')),
                ('age', models.CharField(choices=[('18-29', '18-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50-59', '50-59'), ('60-69', '60-69'), ('70-79', '70-79'), ('80-89', '80-89')], max_length=5, verbose_name='Ваш возраст')),
                ('subscription_info', models.TextField(verbose_name='Как давно вы на меня подписаны и откуда про меня узнали?')),
                ('health_satisfaction', models.CharField(choices=[('no', 'Нет'), ('yes', 'Да'), ('not_sure', 'Затрудняюсь ответить')], max_length=10, verbose_name='Довольны ли вы текущим состоянием ваше здоровья?')),
                ('health_issues', models.TextField(verbose_name='ТОП-3 вопроса по здоровью, которые вы бы хотели решить/улучшить?')),
                ('subscribed_doctors', models.TextField(verbose_name='На кого из докторов вы подписаны в телеграм? (можно просто написать название канала или вставить ссылки)')),
                ('income', models.CharField(choices=[('50k', 'до 50 тысяч'), ('100k', 'до 100 тысяч'), ('150k', 'до 150 тысяч'), ('200k', 'до 200 тысяч'), ('300k', 'до 300 тысяч'), ('300k_plus', 'выше 300 тысяч')], max_length=10, verbose_name='Ваш средний доход в месяц?')),
                ('bought_products', models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3, verbose_name='Покупали ли вы какие-то образовательные продукты у докторов в соцсетях (НЕ консультации)?')),
                ('products_details', models.TextField(blank=True, verbose_name='Если да, то расскажите какие, у кого и за какую стоимость?')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Ваше Имя и Фамилия')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город проживания')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Ваш номер телефона?')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Ссылка на ваш личный телеграм (не канал) в формате https://t.me/abaymukanov или через @')),
                ('policy_agreement', models.BooleanField(default=False, verbose_name='Даю согласие на обработку персональных данных')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Анкета нового продукта',
                'verbose_name_plural': 'Анкеты нового продукта',
            },
        ),
        migrations.CreateModel(
            name='BusinessForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(upload_to=business_forms.models.BusinessForm.get_upload_photo_path)),
                ('spasibo_photo', models.ImageField(upload_to=business_forms.models.BusinessForm.get_upload_spasibo_path)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Конфигурации форм',
                'verbose_name_plural': 'Конфигурации форм',
            },
        ),
    ]
