# Generated by Django 4.2.13 on 2025-10-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='bought_products',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет'), ('another', 'У других докторов в соцсетях')], max_length=100, verbose_name='Покупали ли вы какие-то образовательные продукты у других докторов в соцсетях (НЕ консультации)?'),
        ),
    ]
