# Generated by Django 4.2.13 on 2025-10-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproduct',
            name='source',
            field=models.CharField(choices=[('telegram', 'Телеграм'), ('instagram', 'Инстаграм (запрещен в РФ)'), ('bot_mailing', 'Рассылка в боте'), ('email_mailing', 'Рассылка по почте'), ('vk', 'ВКонтакте')], max_length=20, verbose_name='Вы увидели эту анкету у меня в'),
        ),
    ]
